spring.application.name=cookflip_services
spring.datasource.url=jdbc:postgresql://localhost:5432/cookflip
spring.datasource.username=juanaviles
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true